### ISSUE TITLE
500 error uploading images using imageupload plugin 

### ISSUE THREAD

**Issue by damirt2017** [w8tcha/dnnckeditor#25]
I apologize if this question does not belong to this project. Please feel free to direct me to the right spot. I am trying to make the CKEditor 4.7 work with DNN 9.1.1 and the cut and paste image upload plugin. When I drag and drop an image into the editor, I get a green notification that an image is uploaded, followed by a red notification with a 500 error. The image is successfully uploaded on the server, but it does not show up in the editor.

Looking in the log files, I found this error. I am not sure where this is failing, is it in DNN, DNN CKEditor provider, CKEditor or the imageupload plugin. Any guidance would be greatly appreciated.

2017-12-20 01:58:37,342 [RD0003FF783AA8][Thread:168][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.ArgumentNullException: Value cannot be null.
 Parameter name: input
 at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
 at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement, RegexOptions options)
 at WatchersNET.CKEditor.Browser.Browser.GetJsUploadCode(String fileName, String fileUrl)
 at WatchersNET.CKEditor.Browser.Browser.UploadQuickFile(HttpPostedFile file, String command)
 at WatchersNET.CKEditor.Browser.Browser.Page_Load(Object sender, EventArgs e)
 at System.Web.UI.Control.OnLoad(EventArgs e)
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
 at System.Web.UI.Page.HandleError(Exception e)
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
 at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
 at System.Web.UI.Page.ProcessRequest()
 at System.Web.UI.Page.ProcessRequest(HttpContext context)
 at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
 at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

The error in the browser console is:
plugin.js?t=H8DA:67 POST http://martinpowersports.edevpod1-dx1dnn1.dx1app.com/Providers/HtmlEditorProviders/CKEditor/Browser/Browser.aspx?Command=ImageUpload&tabid=131818&PortalID=1502&mid=248688&ckid=txtContent&mode=Portal&lang=en-US&responseType=json 500 (Internal Server Error)
(anonymous) @ plugin.js?t=H8DA:67
n @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13
upload @ plugin.js?t=H8DA:556
(anonymous) @ plugin.js?t=H8DA:480
a.(anonymous function) @ ckeditor.js:11
n @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
changeStatus @ plugin.js?t=H8DA:683
reader.onload @ plugin.js?t=H8DA:525
FileReader (async)
load @ plugin.js?t=H8DA:528
loadAndUpload @ plugin.js?t=H8DA:483
(anonymous) @ plugin.js?t=H8DA:194
n @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13
q @ ckeditor.js:687
d @ ckeditor.js:705
(anonymous) @ ckeditor.js:709
n @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13
f @ ckeditor.js:705
(anonymous) @ ckeditor.js:708
n @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
(anonymous) @ ckeditor.js:64
18:09:17.354

**Comment by w8tcha** [comment]
Sorry but that can not work the api is different for the  upload image plugin is different. Support for this plugin will be added in the Provider 2.01.12

**Comment by damirt2017** [comment]
Thanks for adding this enhancement. I tested it and it works great.
